
"use client";

import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { Sidebar } from '@/components/layout/sidebar';
import { StatCard } from '@/components/dashboard/stat-card';
import { 
  Briefcase, 
  ShieldAlert, 
  TrendingUp,
  Database,
  ChevronRight,
  Scale,
  RefreshCcw,
  BrainCircuit,
  FileDown,
  Users,
  StickyNote
} from 'lucide-react';
import { useRouter } from 'next/navigation';
import { LegalCase, CaseNote } from '@/lib/case-logic';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { fetchRepoCases, fetchRepoNotes } from '@/app/actions/case-actions';

export default function Dashboard() {
  const [cases, setCases] = useState<LegalCase[]>([]);
  const [notes, setNotes] = useState<CaseNote[]>([]);
  const [loading, setLoading] = useState(true);
  const [mounted, setMounted] = useState(false);
  const router = useRouter();

  useEffect(() => {
    setMounted(true);
  }, []);

  const loadData = useCallback(async () => {
    setLoading(true);
    try {
      const [caseData, noteData] = await Promise.all([
        fetchRepoCases(),
        fetchRepoNotes()
      ]);
      
      if (Array.isArray(caseData)) setCases(caseData);
      if (Array.isArray(noteData)) setNotes(noteData);
    } catch (error) {
      console.error('Failed to load data:', error);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    loadData();
  }, [loadData]);

  const metrics = useMemo(() => {
    const total = cases.length;
    const critical = cases.filter(c => c.status === 'Vencido').length;
    const attention = cases.filter(c => c.status === 'Atenção').length;
    const processed = cases.filter(c => c.situacao === 'EM ANDAMENTO').length;
    const riskScore = total ? Math.round(((critical + attention) / total) * 100) : 0;

    const tribunalCounts: Record<string, number> = {};
    const attorneyCounts: Record<string, number> = {};
    cases.forEach(c => {
      tribunalCounts[c.tribunal] = (tribunalCounts[c.tribunal] || 0) + 1;
      attorneyCounts[c.advogado] = (attorneyCounts[c.advogado] || 0) + 1;
    });

    const topTribunals = Object.entries(tribunalCounts).sort((a, b) => b[1] - a[1]).slice(0, 5);
    const topAttorneys = Object.entries(attorneyCounts).sort((a, b) => b[1] - a[1]).slice(0, 5);

    return { total, critical, attention, processed, riskScore, topTribunals, topAttorneys };
  }, [cases]);

  const urgentQueue = useMemo(() => {
    return cases
      .filter(c => c.status === 'Vencido' || c.status === 'Atenção')
      .sort((a, b) => (a.diasFaltando || 0) - (b.diasFaltando || 0))
      .slice(0, 5);
  }, [cases]);

  const handleExportPDF = () => {
    window.print();
  };

  const handleCaseDetailClick = (protocolo: string) => {
    router.push(`/cases?search=${encodeURIComponent(protocolo)}`);
  };

  return (
    <div className="flex h-screen bg-background font-body">
      <Sidebar />
      <main className="flex-1 flex flex-col h-screen overflow-hidden text-white">
        <header className="h-16 border-b border-border bg-sidebar/50 backdrop-blur-md flex items-center justify-between px-8 shrink-0 print:hidden">
          <div className="flex items-center gap-4">
            <h1 className="font-headline font-bold text-xl text-white">Intelligence Unit</h1>
            <Badge variant="outline" className="border-primary/50 text-primary text-[10px] uppercase font-bold tracking-tighter">Live CRM Database</Badge>
          </div>
          <div className="flex items-center gap-3">
            <Button variant="ghost" size="sm" onClick={handleExportPDF} className="text-muted-foreground hover:text-white border border-border h-8 font-bold">
              <FileDown size={14} className="mr-2" /> Export Unified Report
            </Button>
            <Button variant="ghost" size="icon" onClick={loadData} className="text-muted-foreground hover:text-white">
              <RefreshCcw className={cn("w-4 h-4", loading && "animate-spin")} />
            </Button>
          </div>
        </header>

        <div className="flex-1 overflow-auto p-8 space-y-8 print:p-0">
          {/* Print-Only Header */}
          <div className="hidden print:block mb-10 border-b-2 border-black pb-6">
            <div className="flex justify-between items-end mb-4">
              <div>
                <h1 className="text-3xl font-bold text-black uppercase tracking-tight">Consolidated Procedural Report</h1>
                <p className="text-sm text-gray-600 mt-1">Generated by LexisPredict Intelligence Engine</p>
              </div>
              <div className="text-right">
                <p className="text-xs font-bold text-black uppercase">Reference Date</p>
                <p className="text-lg font-medium text-black">{mounted ? new Date().toLocaleDateString() : '...'}</p>
              </div>
            </div>
          </div>

          <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <StatCard 
              title="Total de Processos" 
              value={loading ? "..." : metrics.total} 
              icon={<Briefcase size={20} />} 
              trend="Global Repository"
              trendUp
            />
            <StatCard 
              title="Alertas Críticos" 
              value={loading ? "..." : metrics.critical} 
              icon={<ShieldAlert size={20} />} 
              color="destructive"
              trend="Requires Action"
            />
            <StatCard 
              title="Taxa de Risco" 
              value={loading ? "..." : `${metrics.riskScore}%`} 
              icon={<TrendingUp size={20} />} 
              color="accent"
            />
            <StatCard 
              title="Ativos" 
              value={loading ? "..." : metrics.processed} 
              icon={<Scale size={20} />} 
              color="success"
              trend="Ongoing Procedures"
              trendUp
            />
          </section>

          <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
            <section className="xl:col-span-2 bg-card border border-border rounded-2xl p-6 shadow-xl print:bg-white print:border-gray-200">
              <div className="flex items-center justify-between mb-6 print:hidden">
                <div>
                  <h2 className="font-headline font-bold text-lg text-white">Priority Queue</h2>
                  <p className="text-xs text-muted-foreground">Highest risk cases requiring immediate attention.</p>
                </div>
                <Badge variant="outline" className="text-primary border-primary/20 bg-primary/5">
                  Cloud Sync Active
                </Badge>
              </div>

              {urgentQueue.length > 0 ? (
                <div className="space-y-3">
                  <h3 className="hidden print:block text-sm font-bold text-black uppercase mb-4">Urgent Filings (Top 5)</h3>
                  {urgentQueue.map((c) => (
                    <div 
                      key={c.protocolo} 
                      onClick={() => handleCaseDetailClick(c.protocolo)}
                      className="group p-4 bg-secondary/30 border border-border hover:border-primary/50 rounded-xl transition-all flex items-center justify-between cursor-pointer print:bg-gray-50 print:border-gray-200 print:mb-2"
                    >
                      <div className="flex items-center gap-4">
                        <div className={cn(
                          "w-10 h-10 rounded-lg flex items-center justify-center font-bold text-[10px] shrink-0 print:text-black print:bg-gray-200",
                          c.status === 'Vencido' ? "bg-destructive/10 text-destructive" : "bg-accent/10 text-accent"
                        )}>
                          {c.tribunal}
                        </div>
                        <div>
                          <p className="font-bold text-sm text-white group-hover:text-primary transition-colors print:text-black">{c.cliente}</p>
                          <p className="text-[10px] text-muted-foreground font-mono uppercase tracking-widest print:text-gray-500">{c.protocolo}</p>
                        </div>
                      </div>
                      <div className="flex items-center gap-6">
                        <div className="text-right hidden sm:block">
                          <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider mb-1 print:text-gray-500">Deadline</p>
                          <p className="text-sm font-medium text-white print:text-black">{c.proximoPrazo}</p>
                        </div>
                        <div className="flex items-center gap-3">
                          <Badge className={cn(
                            "px-3 py-1 font-bold rounded-md print:bg-gray-200 print:text-black",
                            c.status === 'Vencido' ? "bg-destructive/20 text-destructive border-destructive/20" : "bg-accent/20 text-accent border-accent/20"
                          )}>
                            {c.diasFaltando !== null && c.diasFaltando < 0 ? `${Math.abs(c.diasFaltando)}d ATRASADO` : `${c.diasFaltando}d RESTANDO`}
                          </Badge>
                          <ChevronRight size={16} className="text-muted-foreground group-hover:text-primary transition-colors print:hidden" />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="h-64 flex flex-col items-center justify-center border-2 border-dashed border-border rounded-2xl bg-secondary/10">
                  <div className="p-4 bg-secondary rounded-full mb-4">
                    <Scale className="text-muted-foreground w-8 h-8" />
                  </div>
                  <h3 className="text-white font-bold">{loading ? "Synchronizing..." : "No High-Risk Cases"}</h3>
                  <p className="text-sm text-muted-foreground">{loading ? "Connecting to cloud..." : "Queue is clear. All deadlines are healthy."}</p>
                </div>
              )}
            </section>

            <section className="bg-gradient-to-br from-primary to-accent rounded-2xl p-8 text-white relative overflow-hidden flex flex-col justify-center print:hidden">
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/10 rounded-full -translate-y-1/2 translate-x-1/2 blur-2xl" />
              <div className="absolute bottom-0 left-0 w-24 h-24 bg-white/10 rounded-full translate-y-1/2 -translate-x-1/2 blur-xl" />
              
              <div className="relative z-10 space-y-6">
                <div className="p-3 bg-white/20 w-fit rounded-xl backdrop-blur-md border border-white/20">
                  <Database className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h2 className="text-2xl font-headline font-bold">Cloud CRM Engine</h2>
                  <p className="text-sm text-white/80 font-medium leading-relaxed mt-2">
                    Procedural data is automatically synchronized via <strong>Supabase</strong> across all legal workstations.
                  </p>
                </div>
              </div>
            </section>
          </div>

          {/* Print-Only Analytics Section */}
          <div className="hidden print:grid grid-cols-2 gap-10 mt-10">
            <div className="space-y-4">
              <div className="flex items-center gap-2 mb-2">
                <Scale size={16} className="text-black" />
                <h2 className="text-sm font-bold uppercase tracking-widest text-black">Tribunal Load</h2>
              </div>
              {metrics.topTribunals.map(([name, count]) => (
                <div key={name} className="flex justify-between text-xs border-b border-gray-100 py-1">
                  <span className="text-gray-700">{name}</span>
                  <span className="font-bold text-black">{count} cases</span>
                </div>
              ))}
            </div>
            <div className="space-y-4">
              <div className="flex items-center gap-2 mb-2">
                <Users size={16} className="text-black" />
                <h2 className="text-sm font-bold uppercase tracking-widest text-black">Attorney Workload</h2>
              </div>
              {metrics.topAttorneys.map(([name, count]) => (
                <div key={name} className="flex justify-between text-xs border-b border-gray-100 py-1">
                  <span className="text-gray-700">{name}</span>
                  <span className="font-bold text-black">{count} cases</span>
                </div>
              ))}
            </div>
          </div>

          {/* Print-Only Notes Section */}
          <div className="hidden print:block mt-12 pt-8 border-t border-black">
            <div className="flex items-center gap-2 mb-6">
              <StickyNote size={18} className="text-black" />
              <h2 className="text-lg font-bold uppercase tracking-widest text-black">Procedural Annotations & Updates</h2>
            </div>
            {notes.length > 0 ? (
              <div className="grid grid-cols-2 gap-6">
                {notes.map((note) => (
                  <div key={note.id} className="border border-gray-200 p-4 rounded-lg bg-gray-50">
                    <p className="text-[10px] font-bold text-gray-500 uppercase mb-1">{note.updatedAt}</p>
                    <h3 className="font-bold text-sm text-black mb-2">{note.title}</h3>
                    <p className="text-xs text-gray-700 leading-relaxed whitespace-pre-wrap">{note.content}</p>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-gray-400 italic">No annotations recorded for this period.</p>
            )}
          </div>
        </div>
      </main>
    </div>
  );
}
